//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Guid AssetId { get; set; }
        public string Description { get; set; }
        public int AssetTypeId { get; set; }
        public int RenterId { get; set; }
        public string PlateNumber { get; set; }
        public string SuiteNo { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual Renter Renter { get; set; }
    }
}
